import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Elliots guitar beating it up!</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Elliot beat - The best beats in the universe!
        </h1>

        <p>The greatest beats - køb det mand! </p>
        <iframe src="https://player.beatstars.com/?storeId=131749" width="100%" height="800" style="max-width:1024px;" />

      
      </main>

      <footer className={styles.footer}>
   
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
     
      </footer>
    </div>
  )
}
