import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Guitar beats by Elliot</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Buy beats
        </h1>

        <iframe src="https://player.beatstars.com/?storeId=131749" width="100%" height="800px"  />

      
      </main>

      <footer className={styles.footer}>
   
      
     
      </footer>
    </div>
  )
}
